/**
 * types/index.ts
 *
 * Shared TypeScript type definitions for the Whop Email Engine.
 *
 * Database-level types are generated by Prisma — import from @prisma/client.
 * This file holds application-layer types: API shapes, UI state, etc.
 */

// ---------------------------------------------------------------------------
// Generic API response wrapper
// ---------------------------------------------------------------------------

export type ApiResponse<T> =
  | { success: true; data: T }
  | { success: false; error: string; code?: string };

// ---------------------------------------------------------------------------
// Pagination
// ---------------------------------------------------------------------------

export interface PaginationParams {
  page: number;
  limit: number;
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}

// ---------------------------------------------------------------------------
// Workspace / Tenant
// ---------------------------------------------------------------------------

export interface WorkspaceContext {
  workspaceId: string;
  userId: string;
  role: WorkspaceMemberRole;
}

export type WorkspaceMemberRole = "OWNER" | "ADMIN" | "MEMBER";

// ---------------------------------------------------------------------------
// Campaign status
// ---------------------------------------------------------------------------

export type CampaignStatus =
  | "DRAFT"
  | "SCHEDULED"
  | "SENDING"
  | "COMPLETED"
  | "FAILED"
  | "PAUSED";

// ---------------------------------------------------------------------------
// Email send status
// ---------------------------------------------------------------------------

export type EmailSendStatus =
  | "PENDING"
  | "SENT"
  | "DELIVERED"
  | "OPENED"
  | "CLICKED"
  | "BOUNCED"
  | "FAILED"
  | "UNSUBSCRIBED";

// ---------------------------------------------------------------------------
// Email provider
// ---------------------------------------------------------------------------

export type EmailProvider = "RESEND" | "SMTP";

// ---------------------------------------------------------------------------
// Contact
// ---------------------------------------------------------------------------

export interface ContactFilters {
  workspaceId: string;
  search?: string;
  tags?: string[];
  isSubscribed?: boolean;
  page?: number;
  limit?: number;
}

// ---------------------------------------------------------------------------
// Whop API types (typed shapes for Whop API responses)
// ---------------------------------------------------------------------------

export interface WhopMember {
  id: string;
  email: string;
  username?: string;
  name?: string;
  profilePicture?: string;
  createdAt: string;
}

export interface WhopProduct {
  id: string;
  name: string;
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Sync
// ---------------------------------------------------------------------------

export type SyncStatus = "IDLE" | "RUNNING" | "SUCCESS" | "FAILED";

export interface SyncResult {
  status: SyncStatus;
  synced: number;
  skipped: number;
  errors: number;
  startedAt: Date;
  completedAt?: Date;
  errorDetails?: string[];
}
